# vim:tw=0:ts=2:sw=2:et:norl
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/doblabs/easy-as-pypi#🥧
# License: MIT

---

name: Run reversioning workflows

on:
  workflow_call:

jobs:

  blather:
    name: Blather
    runs-on: ubuntu-latest
    steps:
      - name: Dump github.event
        run: echo "${GITHUB_EVENT}"
        shell: bash
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}

  run-reversioning:
    name: Run reversioning workflows

    runs-on: ubuntu-latest

    steps:
      # CXREF: https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3

      # CXREF: https://github.com/marketplace/actions/yaml-read
      - name: Read dependency config
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_deps_js
        with:
          config: ${{ github.workspace }}/.github/doblabs-dependencies.yml

      # CXREF: https://github.com/marketplace/actions/repository-dispatch
      - name: Dispatch remote repo workflows
        uses: peter-evans/repository-dispatch@v2
        with:
          # Personal access token created for *my user* with public_repo permissions.
          token: ${{ secrets.PAT__PUBLIC_REPO }}
          repository: "${{ steps.read_deps_js.outputs['${{ github.repository }}'] }}"
          event-type: update-org-deps
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
